// noinspection JSUnusedGlobalSymbols
export enum MunicipiosChubut{
  ALTO_RIO_SENGUER = 'Alto Río Senguer',
  CAMARONES = 'Camarones',
  CHOLILA = 'Cholila',
  COMODORO_RIVADAVIA = 'Comodoro Rivadavia',
  CORCOVADO = 'Corcovado',
  DOLAVON = 'Dolavon',
  EL_HOYO = 'El Hoyo',
  EL_MAITEN = 'El Maitén',
  EPUYEN = 'Epuyén',
  ESQUEL = 'Esquel',
  GAIMAN = 'Gaiman',
  GOBERNADOR_COSTA = 'Gobernador Costa',
  GUALJAINA = 'Gualjaina',
  JOSE_DE_SAN_MARTIN = 'José de San Martín',
  LAGO_PUELO = 'Lago Puelo',
  PASO_DE_INDIOS = 'Paso de Indios',
  PUERTO_MADRYN = 'Puerto Madryn',
  PUERTO_PIRAMIDES = 'Puerto Pirámides',
  RADA_TILLY = 'Rada Tilly',
  RAWSON = 'Rawson',
  RIO_MAYO = 'Río Mayo',
  RIO_PICO = 'Río Pico',
  SARMIENTO = 'Sarmiento',
  TECKA = 'Tecka',
  TRELEW = 'Trelew',
  TREVELIN = 'Trevelin',
  VEINTIOCHO_DE_JULIO = 'Veintiocho de Julio',
}
