// noinspection JSUnusedGlobalSymbols
export enum MunicipiosFormosa{
  CLORINDA = 'Clorinda',
  COMANDANTE_FONTANA = 'Comandante Fontana',
  EL_CHORRO = 'El Chorro (General Enrique Mosconi)',
  EL_COLORADO = 'El Colorado',
  EL_ESPINILLO = 'El Espinillo',
  ESTANISLAO_DEL_CAMPO = 'Estanislao del Campo',
  FORMOSA = 'Formosa',
  GENERAL_LUCIO_V_MANSILLA = 'General Lucio V. Mansilla (General Lucio Victorio Mansilla)',
  GENERAL_MANUEL_BELGRANO = 'General Manuel Belgrano',
  HERRADURA = 'Herradura',
  IBARRETA = 'Ibarreta',
  INGENIERO_JUAREZ = 'Ingeniero Juárez (Ingeniero Guillermo Nicasio Juárez)',
  LAGUNA_BLANCA = 'Laguna Blanca',
  LAGUNA_NAINECK = 'Laguna Naineck (Laguna Naick Neck)',
  LAGUNA_YEMA = 'Laguna Yema',
  LAS_LOMITAS = 'Las Lomitas',
  MAYOR_VICENTE_VILLAFANE = 'Mayor Vicente Villafañe (Mayor Villafañe)',
  MISION_SAN_FRANCISCO_DE_LAISHI = 'Misión San Francisco de Laishí',
  MISION_TACAAGLE = 'Misión Tacaaglé',
  PALO_SANTO = 'Palo Santo',
  PIRANE = 'Pirané',
  POZO_DEL_TIGRE = 'Pozo del Tigre',
  RIACHO_HE_HE = 'Riacho He-Hé',
  SAN_MARTIN_2 = 'San Martín 2',
  VILLA_DOS_TRECE = 'Villa Dos Trece',
  VILLA_ESCOLAR = 'Villa Escolar',
  VILLA_GENERAL_GUEMES = 'Villa General Güemes',
}
