// noinspection JSUnusedGlobalSymbols
export enum MunicipiosJujuy{
  ABRA_PAMPA = 'Abra Pampa',
  AGUAS_CALIENTES = 'Aguas Calientes',
  CAIMANCITO = 'Caimancito',
  CALILEGUA = 'Calilegua',
  CIUDAD_PERICO = 'Ciudad Perico',
  EL_AGUILAR = 'El Aguilar',
  EL_CARMEN = 'El Carmen',
  EL_TALAR = 'El Talar',
  FRAILE_PINTADO = 'Fraile Pintado',
  HUMAHUACA = 'Humahuaca',
  LA_ESPERANZA = 'La Esperanza',
  LA_MENDIETA = 'La Mendieta',
  LA_QUIACA = 'La Quiaca',
  LIBERTADOR_GENERAL_SAN_MARTIN = 'Libertador General San Martín (Ledesma)',
  MAIMARA = 'Maimará',
  MONTERRICO = 'Monterrico',
  PALMA_SOLA = 'Palma Sola',
  PALPALA = 'Palpalá',
  PAMPA_BLANCA = 'Pampa Blanca',
  PUESTO_VIEJO = 'Puesto Viejo',
  SAN_ANTONIO = 'San Antonio',
  SAN_PEDRO_DE_JUJUY = 'San Pedro de Jujuy',
  SAN_SALVADOR_DE_JUJUY = 'San Salvador de Jujuy',
  SANTA_CLARA = 'Santa Clara',
  TILCARA = 'Tilcara',
  YALA = 'Yala',
  YUTO = 'Yuto',
}
