// noinspection JSUnusedGlobalSymbols
export enum MunicipiosMendoza{
  GENERAL_ALVEAR = 'General Alvear',
  GODOY_CRUZ = 'Godoy Cruz',
  GUAYMALLEN = 'Guaymallén',
  JUNIN = 'Junín',
  LA_PAZ = 'La Paz',
  LAS_HERAS = 'Las Heras',
  LAVALLE = 'Lavalle',
  LUJAN_DE_CUYO = 'Luján de Cuyo',
  MAIPU = 'Maipú',
  MALARGUE = 'Malargüe',
  MENDOZA = 'Mendoza',
  RIVADAVIA = 'Rivadavia',
  SAN_CARLOS = 'San Carlos',
  SAN_MARTIN = 'San Martín',
  SAN_RAFAEL = 'San Rafael',
  SANTA_ROSA = 'Santa Rosa',
  TUNUYAN = 'Tunuyán',
  TUPUNGATO = 'Tupungato',
}
