// noinspection JSUnusedGlobalSymbols
export enum Provincias{
  BUENOS_AIRES = 'Buenos Aires',
  CATAMARCA = 'Catamarca',
  CHACO = 'Chaco',
  CHUBUT = 'Chubut',
  CIUDAD_AUTONOMA_DE_BUENOS_AIRES = 'Ciudad Autónoma de Buenos Aires',
  CORRIENTES = 'Corrientes',
  CORDOBA = 'Córdoba',
  ENTRE_RIOS = 'Entre Ríos',
  FORMOSA = 'Formosa',
  JUJUY = 'Jujuy',
  LA_PAMPA = 'La Pampa',
  LA_RIOJA = 'La Rioja',
  MENDOZA = 'Mendoza',
  MISIONES = 'Misiones',
  NEUQUEN = 'Neuquén',
  RIO_NEGRO = 'Río Negro',
  SALTA = 'Salta',
  SAN_JUAN = 'San Juan',
  SAN_LUIS = 'San Luis',
  SANTA_CRUZ = 'Santa Cruz',
  SANTA_FE = 'Santa Fe',
  SANTIAGO_DEL_ESTERO = 'Santiago del Estero',
  TIERRA_DEL_FUEGO = 'Tierra del Fuego, Antártida e Islas del Atlántico Sur',
  TUCUMAN = 'Tucumán',
}
