// noinspection JSUnusedGlobalSymbols
export enum MunicipiosSanLuis{
  BUENA_ESPERANZA = 'Buena Esperanza',
  CANDELARIA = 'Candelaria',
  CARPINTERIA = 'Carpintería',
  CONCARAN = 'Concarán',
  EL_TRAPICHE = 'El Trapiche',
  EL_VOLCAN = 'El Volcán',
  JUANA_KOSLAY = 'Juana Koslay',
  JUSTO_DARACT = 'Justo Daract',
  LA_PUNTA = 'La Punta',
  LA_TOMA = 'La Toma',
  LUJAN = 'Luján',
  MERLO = 'Merlo (Villa de Merlo)',
  NASCHEL = 'Naschel',
  POTRERO_DE_LOS_FUNES = 'Potrero de los Funes',
  QUINES = 'Quines',
  SAN_FRANCISCO_DEL_MONTE_DE_ORO = 'San Francisco del Monte de Oro (San Francisco)',
  SAN_LUIS = 'San Luis',
  SAN_MARTIN = 'San Martín',
  SANTA_ROSA_DEL_CONLARA = 'Santa Rosa del Conlara (Santa Rosa)',
  TILISARAO = 'Tilisarao',
  UNION = 'Unión',
  VILLA_GENERAL_ROCA = 'Villa General Roca (Los Manantiales)',
  VILLA_MERCEDES = 'Villa Mercedes',
}
