// noinspection JSUnusedGlobalSymbols
export enum MunicipiosSantiagoDelEstero{
  ANATUYA = 'Añatuya',
  BANDERA = 'Bandera',
  BELTRAN = 'Beltrán',
  CAMPO_GALLO = 'Campo Gallo',
  CLODOMIRA = 'Clodomira',
  COLONIA_DORA = 'Colonia Dora',
  FERNANDEZ = 'Fernández',
  FRIAS = 'Frías',
  INGENIERO_FORRES = 'Ingeniero Forres (Forres)',
  LA_BANDA = 'La Banda',
  LORETO = 'Loreto (Villa San Martín)',
  LOS_JURIES = 'Los Juríes',
  LOS_TELARES = 'Los Telares',
  MONTE_QUEMADO = 'Monte Quemado',
  NUEVA_ESPERANZA = 'Nueva Esperanza',
  PAMPA_DE_LOS_GUANACOS = 'Pampa de los Guanacos',
  PINTO = 'Pinto',
  POZO_HONDO = 'Pozo Hondo',
  QUIMILI = 'Quimilí',
  SAN_PEDRO_DE_GUASAYAN = 'San Pedro de Guasayán',
  SANTIAGO_DEL_ESTERO = 'Santiago del Estero',
  SELVA = 'Selva',
  SUMAMPA = 'Sumampa',
  SUNCHO_CORRAL = 'Suncho Corral',
  TERMAS_DE_RIO_HONDO = 'Termas de Río Hondo',
  TINTINA = 'Tintina',
  VILLA_ATAMISQUI = 'Villa Atamisqui',
  VILLA_OJO_DE_AGUA = 'Villa Ojo de Agua',
}
