// noinspection JSUnusedGlobalSymbols
export enum MunicipiosTucuman{
  AGUILARES = 'Aguilares',
  ALDERETES = 'Alderetes',
  BANDA_DEL_RIO_SALI = 'Banda del Río Salí',
  BELLA_VISTA = 'Bella Vista',
  BURRUYACU = 'Burruyacú',
  CONCEPCION = 'Concepción',
  FAMAILLA = 'Famaillá',
  GRANEROS = 'Graneros',
  JUAN_BAUTISTA_ALBERDI = 'Juan Bautista Alberdi',
  LA_COCHA = 'La Cocha',
  LAS_TALITAS = 'Las Talitas',
  MONTEROS = 'Monteros',
  SAN_ISIDRO_DE_LULES = 'San Isidro de Lules',
  SAN_MIGUEL_DE_TUCUMAN = 'San Miguel de Tucumán',
  SIMOCA = 'Simoca',
  TAFI_VIEJO = 'Tafí Viejo',
  TAFI_DEL_VALLE = 'Tafí del Valle',
  TRANCAS = 'Trancas',
  YERBA_BUENA = 'Yerba Buena',
}
